"""initial schema: runs, messages, opportunities

Revision ID: 0001
Revises:
Create Date: 2026-08-19

Hand-written rather than autogenerated so the shape of Phase 0 is legible
at review time. Future migrations use `alembic revision --autogenerate` and
the mako template.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "runs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(16), nullable=False, server_default="running"),
        sa.Column("messages_fetched", sa.Integer, nullable=False, server_default="0"),
        sa.Column("messages_new", sa.Integer, nullable=False, server_default="0"),
        sa.Column("messages_classified", sa.Integer, nullable=False, server_default="0"),
        sa.Column("messages_extracted", sa.Integer, nullable=False, server_default="0"),
        sa.Column("messages_extraction_failed", sa.Integer, nullable=False, server_default="0"),
        sa.Column("classify_tokens_in", sa.BigInteger, nullable=False, server_default="0"),
        sa.Column("classify_tokens_out", sa.BigInteger, nullable=False, server_default="0"),
        sa.Column("extract_tokens_in", sa.BigInteger, nullable=False, server_default="0"),
        sa.Column("extract_tokens_out", sa.BigInteger, nullable=False, server_default="0"),
        sa.Column("estimated_cost_usd", sa.Numeric(10, 6), nullable=False, server_default="0"),
    )

    op.create_table(
        "messages",
        # PK = RFC 5322 Message-ID — see the CONCEPT comment in db/models.py
        sa.Column("message_id", sa.Text, primary_key=True),
        sa.Column("gmail_id", sa.String(64), nullable=False),
        sa.Column("thread_id", sa.String(64), nullable=False),
        sa.Column("from_email", sa.String(320), nullable=False),
        sa.Column("from_name", sa.String(320), nullable=True),
        sa.Column("subject", sa.Text, nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("body_text", sa.Text, nullable=False),
        sa.Column("raw_headers", postgresql.JSONB, nullable=False),
        sa.Column("status", sa.String(32), nullable=False, server_default="fetched"),
        sa.Column("category", sa.String(64), nullable=True),
        sa.Column("extraction_error", sa.Text, nullable=True),
        sa.Column("classified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "run_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("runs.id"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_messages_gmail_id", "messages", ["gmail_id"], unique=True)
    op.create_index("ix_messages_thread_id", "messages", ["thread_id"])
    op.create_index("ix_messages_received_at", "messages", ["received_at"])
    op.create_index("ix_messages_status", "messages", ["status"])
    op.create_index("ix_messages_category", "messages", ["category"])
    op.create_index("ix_messages_run_id", "messages", ["run_id"])

    op.create_table(
        "opportunities",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "message_id",
            sa.Text,
            sa.ForeignKey("messages.message_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("company", sa.Text, nullable=True),
        sa.Column("end_client", sa.Text, nullable=True),
        sa.Column("role_title", sa.Text, nullable=True),
        sa.Column("location", sa.Text, nullable=True),
        sa.Column("work_model", sa.String(16), nullable=True),
        sa.Column("employment_type", sa.String(16), nullable=True),
        sa.Column("ctc_min_lpa", sa.Numeric(10, 2), nullable=True),
        sa.Column("ctc_max_lpa", sa.Numeric(10, 2), nullable=True),
        sa.Column("currency", sa.String(8), nullable=False, server_default="INR"),
        sa.Column("notice_period", sa.String(64), nullable=True),
        sa.Column("recruiter_name", sa.String(320), nullable=True),
        sa.Column("recruiter_email", sa.String(320), nullable=True),
        sa.Column("recruiter_phone", sa.String(64), nullable=True),
        sa.Column("source_platform", sa.String(64), nullable=True),
        sa.Column("jd_text", sa.Text, nullable=True),
        sa.Column("retry_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index(
        "ix_opportunities_message_id", "opportunities", ["message_id"], unique=True
    )


def downgrade() -> None:
    op.drop_index("ix_opportunities_message_id", table_name="opportunities")
    op.drop_table("opportunities")
    op.drop_index("ix_messages_run_id", table_name="messages")
    op.drop_index("ix_messages_category", table_name="messages")
    op.drop_index("ix_messages_status", table_name="messages")
    op.drop_index("ix_messages_received_at", table_name="messages")
    op.drop_index("ix_messages_thread_id", table_name="messages")
    op.drop_index("ix_messages_gmail_id", table_name="messages")
    op.drop_table("messages")
    op.drop_table("runs")
